Fix file write
tdutrion/flysystem-rackspace pull request #1
Opened 2021-05-06 09:21 UTC by alcalyn

- Fix `writeStream`
- Fix normalize object when getting timestamp

2021-05-06 09:22 UTC, alcalyn commented
Fixes https://github.com/thephpleague/flysystem-rackspace/pull/26

2021-05-07 16:17 UTC, tdutrion approved these changes

2021-05-07 16:21 UTC, tdutrion requested changes

2021-05-07 16:21 UTC, tdutrion commented on src/RackspaceAdapter.php
> +        }
`$config` is not nullable, so I would not worry about testing it. Also `$config->get(` accepts to parameters, the second one being the default value, so this can be simplified a lot:

```suggestion
        $headers = $config->get('headers', []);
```

2021-05-10 08:30 UTC, alcalyn commented on src/RackspaceAdapter.php
> +        }
Updated

2021-05-10 08:33 UTC, tdutrion approved these changes

2021-05-10 08:33 UTC, merged